openapi: 3.0.3
info:
  title: Accounts API
  description: API endpoints for managing and retrieving account information in the Accounting & Invoicing UI
  version: 1.0.0
  contact:
    name: API Support
    email: api@example.com

servers:
  - url: https://api.example.com/v1
    description: Production server
  - url: https://api-staging.example.com/v1
    description: Staging server

paths:
  /tenants/{tenantId}/accounts:
    get:
      summary: List accounts
      description: Retrieve a paginated list of accounts within a tenant
      operationId: listAccounts
      tags:
        - Accounts
      parameters:
        - name: tenantId
          in: path
          required: true
          description: Tenant ID
          schema:
            type: string
            format: uuid
        - name: page
          in: query
          required: false
          description: Page number (1-indexed)
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: pageSize
          in: query
          required: false
          description: Items per page
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 50
        - name: status
          in: query
          required: false
          description: Filter by account status
          schema:
            type: string
            enum: [active, suspended, closed]
        - name: type
          in: query
          required: false
          description: Filter by account type
          schema:
            type: string
            enum: [organization, individual]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountListResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /tenants/{tenantId}/accounts/{accountId}:
    get:
      summary: Get account details
      description: Retrieve detailed information for a specific account
      operationId: getAccount
      tags:
        - Accounts
      parameters:
        - name: tenantId
          in: path
          required: true
          description: Tenant ID
          schema:
            type: string
            format: uuid
        - name: accountId
          in: path
          required: true
          description: Account ID
          schema:
            type: string
            format: uuid
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '404':
          $ref: '#/components/responses/NotFound'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Account:
      type: object
      required:
        - id
        - tenantId
        - name
        - type
        - currentBalance
        - status
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
          format: uuid
          description: Account ID
        tenantId:
          type: string
          format: uuid
          description: Tenant ID
        name:
          type: string
          minLength: 1
          maxLength: 200
          description: Account name
          example: "General Hospital"
        type:
          type: string
          enum: [organization, individual]
          description: Account type
        currentBalance:
          type: integer
          description: Current balance in USD cents
          example: 105000
        lastInvoiceDate:
          type: string
          format: date
          nullable: true
          description: Date of last invoice (ISO 8601)
          example: "2024-01-15"
        status:
          type: string
          enum: [active, suspended, closed]
          description: Account status
        createdAt:
          type: string
          format: date-time
          description: Account creation timestamp (ISO 8601)
        updatedAt:
          type: string
          format: date-time
          description: Last update timestamp (ISO 8601)

    AccountListResponse:
      type: object
      required:
        - items
        - totalCount
        - page
        - pageSize
        - totalPages
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Account'
        totalCount:
          type: integer
          description: Total number of accounts matching filters
        page:
          type: integer
          description: Current page number (1-indexed)
        pageSize:
          type: integer
          description: Items per page
        totalPages:
          type: integer
          description: Total number of pages

    ApiError:
      type: object
      required:
        - statusCode
        - message
        - errorCode
        - timestamp
        - correlationId
      properties:
        statusCode:
          type: integer
          description: HTTP status code
        message:
          type: string
          description: User-friendly error message
        errorCode:
          type: string
          description: Machine-readable error code
        details:
          type: object
          nullable: true
          additionalProperties: true
          description: Additional error details
        timestamp:
          type: string
          format: date-time
          description: Error timestamp (ISO 8601)
        correlationId:
          type: string
          description: Correlation ID for tracing

  responses:
    Unauthorized:
      description: Unauthorized - invalid or missing authentication token
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
    Forbidden:
      description: Forbidden - user does not have permission to access this resource
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
    NotFound:
      description: Not found - requested resource does not exist
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
